// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  requesterId: __t.string().name("requester_id"),
  cardId: __t.string().name("card_id"),
  merchant: __t.string(),
  amount: __t.i32(),
  category: __t.string(),
  reason: __t.string(),
  requestedAt: __t.string().name("requested_at"),
  expiresAt: __t.string().name("expires_at"),
  status: __t.string(),
  resolvedBy: __t.option(__t.string()).name("resolved_by"),
  resolvedAt: __t.option(__t.string()).name("resolved_at"),
});
