// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  memberId: __t.string().name("member_id"),
  cardType: __t.string().name("card_type"),
  nickname: __t.string(),
  priceInr: __t.i32().name("price_inr"),
  priceUsd: __t.f64().name("price_usd"),
  expectedUnits: __t.f64().name("expected_units"),
  memo: __t.string(),
  status: __t.string(),
  depositId: __t.option(__t.string()).name("deposit_id"),
  providerCardId: __t.option(__t.string()).name("provider_card_id"),
  reviewedBy: __t.option(__t.string()).name("reviewed_by"),
  reviewNote: __t.option(__t.string()).name("review_note"),
  createdAt: __t.string().name("created_at"),
  updatedAt: __t.string().name("updated_at"),
});
