// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  nickname: __t.string(),
  variant: __t.string(),
  status: __t.string(),
  last4: __t.string().name("last_4"),
  memberId: __t.option(__t.string()).name("member_id"),
  monthlyCap: __t.option(__t.i32()).name("monthly_cap"),
  spentThisMonth: __t.i32().name("spent_this_month"),
  approvalAbove: __t.option(__t.i32()).name("approval_above"),
  online: __t.bool(),
  contactless: __t.bool(),
  atm: __t.bool(),
  international: __t.bool(),
  maxAuthorization: __t.option(__t.i32()).name("max_authorization"),
  expiryNote: __t.option(__t.string()).name("expiry_note"),
  provider: __t.string(),
  providerCardId: __t.option(__t.string()).name("provider_card_id"),
});
