// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  userId: __t.string(),
  memberId: __t.string(),
  cardType: __t.string(),
  nickname: __t.string(),
  priceInr: __t.i32(),
  priceUsd: __t.f64(),
  expectedUnits: __t.f64(),
  memo: __t.string(),
  actorName: __t.string(),
};
