// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  txHash: __t.string().name("tx_hash"),
  opId: __t.string().name("op_id"),
  fromAddress: __t.string().name("from_address"),
  assetCode: __t.string().name("asset_code"),
  amountUnits: __t.f64().name("amount_units"),
  creditedInr: __t.i32().name("credited_inr"),
  memo: __t.option(__t.string()),
  userId: __t.option(__t.string()).name("user_id"),
  status: __t.string(),
  at: __t.string(),
});
