// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  actionId: __t.string(),
  factsHash: __t.string(),
  idempotencyKey: __t.string(),
  userId: __t.string(),
  sessionMemberId: __t.string(),
  actor: __t.string(),
  receiptJson: __t.string(),
  expiresAtLabel: __t.option(__t.string()),
  providerCardId: __t.option(__t.string()),
  providerName: __t.option(__t.string()),
  newCardId: __t.option(__t.string()),
  newLast4: __t.option(__t.string()),
  inviteMemberId: __t.option(__t.string()),
  inviteCode: __t.option(__t.string()),
  withdrawalId: __t.option(__t.string()),
};
