// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.2 (commit 524b4487d949b61a07d4f39c862d1290259dfd20).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptInviteReducer from "./accept_invite_reducer.js";
import AdminApproveOrderReducer from "./admin_approve_order_reducer.js";
import AdminRejectOrderReducer from "./admin_reject_order_reducer.js";
import AdminReviewKycReducer from "./admin_review_kyc_reducer.js";
import AdminSetProviderPoolReducer from "./admin_set_provider_pool_reducer.js";
import AppendAuditReducer from "./append_audit_reducer.js";
import ApplyFreezeReducer from "./apply_freeze_reducer.js";
import ApproveOnceReducer from "./approve_once_reducer.js";
import BindPrivyDidReducer from "./bind_privy_did_reducer.js";
import BootstrapPoolWalletReducer from "./bootstrap_pool_wallet_reducer.js";
import CancelActionReducer from "./cancel_action_reducer.js";
import CreateCardOrderReducer from "./create_card_order_reducer.js";
import DeclineApprovalReducer from "./decline_approval_reducer.js";
import DevLinkCardProviderReducer from "./dev_link_card_provider_reducer.js";
import DevResetReducer from "./dev_reset_reducer.js";
import ExecuteActionReducer from "./execute_action_reducer.js";
import ExpireActionReducer from "./expire_action_reducer.js";
import ExpireApprovalReducer from "./expire_approval_reducer.js";
import LinkWalletReducer from "./link_wallet_reducer.js";
import PrepareActionRowReducer from "./prepare_action_row_reducer.js";
import RecordDepositReducer from "./record_deposit_reducer.js";
import RecordOrderPaymentReducer from "./record_order_payment_reducer.js";
import SetCategoryReducer from "./set_category_reducer.js";
import SetChannelReducer from "./set_channel_reducer.js";
import SetSyncCursorReducer from "./set_sync_cursor_reducer.js";
import SubmitKycReducer from "./submit_kyc_reducer.js";
import WithdrawalMarkFailedReducer from "./withdrawal_mark_failed_reducer.js";
import WithdrawalMarkSentReducer from "./withdrawal_mark_sent_reducer.js";

// Import all procedure arg schemas

// Import all table schema definitions
import ApprovalsRow from "./approvals_table.js";
import AuditEventsRow from "./audit_events_table.js";
import BalancesRow from "./balances_table.js";
import CardOrdersRow from "./card_orders_table.js";
import CardsRow from "./cards_table.js";
import DepositsRow from "./deposits_table.js";
import HouseholdRow from "./household_table.js";
import IdempotencyRow from "./idempotency_table.js";
import InvitesRow from "./invites_table.js";
import MemberCategoriesRow from "./member_categories_table.js";
import MembersRow from "./members_table.js";
import ModuleConfigRow from "./module_config_table.js";
import PoolRow from "./pool_table.js";
import PreparedActionsRow from "./prepared_actions_table.js";
import ProviderPoolRow from "./provider_pool_table.js";
import SyncStateRow from "./sync_state_table.js";
import TransactionsRow from "./transactions_table.js";
import UserWalletsRow from "./user_wallets_table.js";
import UsersRow from "./users_table.js";
import WithdrawalsRow from "./withdrawals_table.js";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  approvals: __table({
    name: 'approvals',
    indexes: [
      { accessor: 'id', name: 'approvals_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'approvals_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApprovalsRow),
  auditEvents: __table({
    name: 'audit_events',
    indexes: [
      { accessor: 'id', name: 'audit_events_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'audit_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuditEventsRow),
  balances: __table({
    name: 'balances',
    indexes: [
      { accessor: 'scope', name: 'balances_scope_idx_btree', algorithm: 'btree', columns: [
        'scope',
      ] },
    ],
    constraints: [
      { name: 'balances_scope_key', constraint: 'unique', columns: ['scope'] },
    ],
  }, BalancesRow),
  cardOrders: __table({
    name: 'card_orders',
    indexes: [
      { accessor: 'id', name: 'card_orders_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'memo', name: 'card_orders_memo_idx_btree', algorithm: 'btree', columns: [
        'memo',
      ] },
      { accessor: 'userId', name: 'card_orders_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'card_orders_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'card_orders_memo_key', constraint: 'unique', columns: ['memo'] },
    ],
  }, CardOrdersRow),
  cards: __table({
    name: 'cards',
    indexes: [
      { accessor: 'id', name: 'cards_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'cards_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CardsRow),
  deposits: __table({
    name: 'deposits',
    indexes: [
      { accessor: 'id', name: 'deposits_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'opId', name: 'deposits_op_id_idx_btree', algorithm: 'btree', columns: [
        'opId',
      ] },
    ],
    constraints: [
      { name: 'deposits_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'deposits_op_id_key', constraint: 'unique', columns: ['opId'] },
    ],
  }, DepositsRow),
  household: __table({
    name: 'household',
    indexes: [
      { accessor: 'id', name: 'household_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'household_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HouseholdRow),
  idempotency: __table({
    name: 'idempotency',
    indexes: [
      { accessor: 'key', name: 'idempotency_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'idempotency_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, IdempotencyRow),
  invites: __table({
    name: 'invites',
    indexes: [
      { accessor: 'code', name: 'invites_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
    ],
    constraints: [
      { name: 'invites_code_key', constraint: 'unique', columns: ['code'] },
    ],
  }, InvitesRow),
  memberCategories: __table({
    name: 'member_categories',
    indexes: [
      { accessor: 'id', name: 'member_categories_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'memberId', name: 'member_categories_member_id_idx_btree', algorithm: 'btree', columns: [
        'memberId',
      ] },
    ],
    constraints: [
      { name: 'member_categories_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MemberCategoriesRow),
  members: __table({
    name: 'members',
    indexes: [
      { accessor: 'id', name: 'members_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'members_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MembersRow),
  moduleConfig: __table({
    name: 'module_config',
    indexes: [
      { accessor: 'id', name: 'module_config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'module_config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ModuleConfigRow),
  pool: __table({
    name: 'pool',
    indexes: [
      { accessor: 'id', name: 'pool_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pool_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PoolRow),
  preparedActions: __table({
    name: 'prepared_actions',
    indexes: [
      { accessor: 'id', name: 'prepared_actions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'prepared_actions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PreparedActionsRow),
  providerPool: __table({
    name: 'provider_pool',
    indexes: [
      { accessor: 'id', name: 'provider_pool_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'provider_pool_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProviderPoolRow),
  syncState: __table({
    name: 'sync_state',
    indexes: [
      { accessor: 'k', name: 'sync_state_k_idx_btree', algorithm: 'btree', columns: [
        'k',
      ] },
    ],
    constraints: [
      { name: 'sync_state_k_key', constraint: 'unique', columns: ['k'] },
    ],
  }, SyncStateRow),
  transactions: __table({
    name: 'transactions',
    indexes: [
      { accessor: 'cardId', name: 'transactions_card_id_idx_btree', algorithm: 'btree', columns: [
        'cardId',
      ] },
      { accessor: 'id', name: 'transactions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'memberId', name: 'transactions_member_id_idx_btree', algorithm: 'btree', columns: [
        'memberId',
      ] },
    ],
    constraints: [
      { name: 'transactions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TransactionsRow),
  userWallets: __table({
    name: 'user_wallets',
    indexes: [
      { accessor: 'address', name: 'user_wallets_address_idx_btree', algorithm: 'btree', columns: [
        'address',
      ] },
      { accessor: 'id', name: 'user_wallets_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'userId', name: 'user_wallets_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_wallets_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserWalletsRow),
  users: __table({
    name: 'users',
    indexes: [
      { accessor: 'depositMemo', name: 'users_deposit_memo_idx_btree', algorithm: 'btree', columns: [
        'depositMemo',
      ] },
      { accessor: 'id', name: 'users_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'users_deposit_memo_key', constraint: 'unique', columns: ['depositMemo'] },
      { name: 'users_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UsersRow),
  withdrawals: __table({
    name: 'withdrawals',
    indexes: [
      { accessor: 'id', name: 'withdrawals_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'withdrawals_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WithdrawalsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_invite", AcceptInviteReducer),
  __reducerSchema("admin_approve_order", AdminApproveOrderReducer),
  __reducerSchema("admin_reject_order", AdminRejectOrderReducer),
  __reducerSchema("admin_review_kyc", AdminReviewKycReducer),
  __reducerSchema("admin_set_provider_pool", AdminSetProviderPoolReducer),
  __reducerSchema("append_audit", AppendAuditReducer),
  __reducerSchema("apply_freeze", ApplyFreezeReducer),
  __reducerSchema("approve_once", ApproveOnceReducer),
  __reducerSchema("bind_privy_did", BindPrivyDidReducer),
  __reducerSchema("bootstrap_pool_wallet", BootstrapPoolWalletReducer),
  __reducerSchema("cancel_action", CancelActionReducer),
  __reducerSchema("create_card_order", CreateCardOrderReducer),
  __reducerSchema("decline_approval", DeclineApprovalReducer),
  __reducerSchema("dev_link_card_provider", DevLinkCardProviderReducer),
  __reducerSchema("dev_reset", DevResetReducer),
  __reducerSchema("execute_action", ExecuteActionReducer),
  __reducerSchema("expire_action", ExpireActionReducer),
  __reducerSchema("expire_approval", ExpireApprovalReducer),
  __reducerSchema("link_wallet", LinkWalletReducer),
  __reducerSchema("prepare_action_row", PrepareActionRowReducer),
  __reducerSchema("record_deposit", RecordDepositReducer),
  __reducerSchema("record_order_payment", RecordOrderPaymentReducer),
  __reducerSchema("set_category", SetCategoryReducer),
  __reducerSchema("set_channel", SetChannelReducer),
  __reducerSchema("set_sync_cursor", SetSyncCursorReducer),
  __reducerSchema("submit_kyc", SubmitKycReducer),
  __reducerSchema("withdrawal_mark_failed", WithdrawalMarkFailedReducer),
  __reducerSchema("withdrawal_mark_sent", WithdrawalMarkSentReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `auditEvents` instead. This alias will be removed in the next major version. */
    readonly "audit_events": Omit<typeof tablesSchema.schemaType.tables["auditEvents"], "accessorName"> & { readonly accessorName: "audit_events" };
    /** @deprecated Use `cardOrders` instead. This alias will be removed in the next major version. */
    readonly "card_orders": Omit<typeof tablesSchema.schemaType.tables["cardOrders"], "accessorName"> & { readonly accessorName: "card_orders" };
    /** @deprecated Use `memberCategories` instead. This alias will be removed in the next major version. */
    readonly "member_categories": Omit<typeof tablesSchema.schemaType.tables["memberCategories"], "accessorName"> & { readonly accessorName: "member_categories" };
    /** @deprecated Use `moduleConfig` instead. This alias will be removed in the next major version. */
    readonly "module_config": Omit<typeof tablesSchema.schemaType.tables["moduleConfig"], "accessorName"> & { readonly accessorName: "module_config" };
    /** @deprecated Use `preparedActions` instead. This alias will be removed in the next major version. */
    readonly "prepared_actions": Omit<typeof tablesSchema.schemaType.tables["preparedActions"], "accessorName"> & { readonly accessorName: "prepared_actions" };
    /** @deprecated Use `providerPool` instead. This alias will be removed in the next major version. */
    readonly "provider_pool": Omit<typeof tablesSchema.schemaType.tables["providerPool"], "accessorName"> & { readonly accessorName: "provider_pool" };
    /** @deprecated Use `syncState` instead. This alias will be removed in the next major version. */
    readonly "sync_state": Omit<typeof tablesSchema.schemaType.tables["syncState"], "accessorName"> & { readonly accessorName: "sync_state" };
    /** @deprecated Use `userWallets` instead. This alias will be removed in the next major version. */
    readonly "user_wallets": Omit<typeof tablesSchema.schemaType.tables["userWallets"], "accessorName"> & { readonly accessorName: "user_wallets" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.2" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "audit_events": "auditEvents",
  "card_orders": "cardOrders",
  "member_categories": "memberCategories",
  "module_config": "moduleConfig",
  "prepared_actions": "preparedActions",
  "provider_pool": "providerPool",
  "sync_state": "syncState",
  "user_wallets": "userWallets",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `auditEvents` instead. This alias will be removed in the next major version. */
  readonly "audit_events": __DbViewBase["auditEvents"];
  /** @deprecated Use `cardOrders` instead. This alias will be removed in the next major version. */
  readonly "card_orders": __DbViewBase["cardOrders"];
  /** @deprecated Use `memberCategories` instead. This alias will be removed in the next major version. */
  readonly "member_categories": __DbViewBase["memberCategories"];
  /** @deprecated Use `moduleConfig` instead. This alias will be removed in the next major version. */
  readonly "module_config": __DbViewBase["moduleConfig"];
  /** @deprecated Use `preparedActions` instead. This alias will be removed in the next major version. */
  readonly "prepared_actions": __DbViewBase["preparedActions"];
  /** @deprecated Use `providerPool` instead. This alias will be removed in the next major version. */
  readonly "provider_pool": __DbViewBase["providerPool"];
  /** @deprecated Use `syncState` instead. This alias will be removed in the next major version. */
  readonly "sync_state": __DbViewBase["syncState"];
  /** @deprecated Use `userWallets` instead. This alias will be removed in the next major version. */
  readonly "user_wallets": __DbViewBase["userWallets"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `auditEvents` instead. This alias will be removed in the next major version. */
  readonly "audit_events": __TablesBase["auditEvents"];
  /** @deprecated Use `cardOrders` instead. This alias will be removed in the next major version. */
  readonly "card_orders": __TablesBase["cardOrders"];
  /** @deprecated Use `memberCategories` instead. This alias will be removed in the next major version. */
  readonly "member_categories": __TablesBase["memberCategories"];
  /** @deprecated Use `moduleConfig` instead. This alias will be removed in the next major version. */
  readonly "module_config": __TablesBase["moduleConfig"];
  /** @deprecated Use `preparedActions` instead. This alias will be removed in the next major version. */
  readonly "prepared_actions": __TablesBase["preparedActions"];
  /** @deprecated Use `providerPool` instead. This alias will be removed in the next major version. */
  readonly "provider_pool": __TablesBase["providerPool"];
  /** @deprecated Use `syncState` instead. This alias will be removed in the next major version. */
  readonly "sync_state": __TablesBase["syncState"];
  /** @deprecated Use `userWallets` instead. This alias will be removed in the next major version. */
  readonly "user_wallets": __TablesBase["userWallets"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

