// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  memberId: __t.string().name("member_id"),
  createdBy: __t.string().name("created_by"),
  status: __t.string(),
  createdAt: __t.string().name("created_at"),
  acceptedAt: __t.option(__t.string()).name("accepted_at"),
});
