// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  role: __t.string(),
  relationship: __t.option(__t.string()),
  monthlyLimit: __t.option(__t.i32()).name("monthly_limit"),
  spentThisMonth: __t.i32().name("spent_this_month"),
  tempAllowanceAmount: __t.option(__t.i32()).name("temp_allowance_amount"),
  tempAllowanceExpiresAt: __t.option(__t.string()).name("temp_allowance_expires_at"),
  status: __t.string(),
});
