// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  network: __t.string(),
  account: __t.string(),
  assetCode: __t.string().name("asset_code"),
  assetIssuer: __t.option(__t.string()).name("asset_issuer"),
  cryptoReserveUnits: __t.f64().name("crypto_reserve_units"),
  fiatFloatInr: __t.i32().name("fiat_float_inr"),
  rateInrPerUnit: __t.f64().name("rate_inr_per_unit"),
  privyWalletId: __t.option(__t.string()).name("privy_wallet_id"),
});
