// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  kind: __t.string(),
  source: __t.string(),
  payloadJson: __t.string(),
  subject: __t.string(),
  factsJson: __t.string(),
  factsHash: __t.string(),
  cta: __t.string(),
  note: __t.string(),
  createdBy: __t.string(),
  expiresAt: __t.string(),
};
