// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  kind: __t.string(),
  source: __t.string(),
  payloadJson: __t.string().name("payload_json"),
  subject: __t.string(),
  factsJson: __t.string().name("facts_json"),
  factsHash: __t.string().name("facts_hash"),
  cta: __t.string(),
  note: __t.string(),
  status: __t.string(),
  createdBy: __t.string().name("created_by"),
  createdAt: __t.string().name("created_at"),
  expiresAt: __t.string().name("expires_at"),
  executedAt: __t.option(__t.string()).name("executed_at"),
  receiptJson: __t.option(__t.string()).name("receipt_json"),
});
