// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  txHash: __t.string(),
  opId: __t.string(),
  fromAddress: __t.string(),
  assetCode: __t.string(),
  amountUnits: __t.f64(),
  creditedInr: __t.i32(),
  memo: __t.option(__t.string()),
  userId: __t.option(__t.string()),
  memberId: __t.option(__t.string()),
  scope: __t.option(__t.string()),
  at: __t.string(),
  credited: __t.bool(),
};
