// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  merchant: __t.string(),
  memberId: __t.string().name("member_id"),
  cardId: __t.string().name("card_id"),
  amount: __t.i32(),
  direction: __t.string(),
  category: __t.string(),
  status: __t.string(),
  declineReason: __t.option(__t.string()).name("decline_reason"),
  approvedBy: __t.option(__t.string()).name("approved_by"),
  at: __t.string(),
});
