// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Approvals = __t.object("Approvals", {
  id: __t.string(),
  requesterId: __t.string(),
  cardId: __t.string(),
  merchant: __t.string(),
  amount: __t.i32(),
  category: __t.string(),
  reason: __t.string(),
  requestedAt: __t.string(),
  expiresAt: __t.string(),
  status: __t.string(),
  resolvedBy: __t.option(__t.string()),
  resolvedAt: __t.option(__t.string()),
});
export type Approvals = __Infer<typeof Approvals>;

export const AuditEvents = __t.object("AuditEvents", {
  id: __t.u64(),
  kind: __t.string(),
  title: __t.string(),
  subtitle: __t.option(__t.string()),
  amount: __t.option(__t.i32()),
  memberId: __t.option(__t.string()),
  actor: __t.string(),
  at: __t.string(),
});
export type AuditEvents = __Infer<typeof AuditEvents>;

export const Balances = __t.object("Balances", {
  scope: __t.string(),
  amount: __t.i32(),
});
export type Balances = __Infer<typeof Balances>;

export const CardOrders = __t.object("CardOrders", {
  id: __t.string(),
  userId: __t.string(),
  memberId: __t.string(),
  cardType: __t.string(),
  nickname: __t.string(),
  priceInr: __t.i32(),
  priceUsd: __t.f64(),
  expectedUnits: __t.f64(),
  memo: __t.string(),
  status: __t.string(),
  depositId: __t.option(__t.string()),
  providerCardId: __t.option(__t.string()),
  reviewedBy: __t.option(__t.string()),
  reviewNote: __t.option(__t.string()),
  createdAt: __t.string(),
  updatedAt: __t.string(),
});
export type CardOrders = __Infer<typeof CardOrders>;

export const Cards = __t.object("Cards", {
  id: __t.string(),
  nickname: __t.string(),
  variant: __t.string(),
  status: __t.string(),
  last4: __t.string(),
  memberId: __t.option(__t.string()),
  monthlyCap: __t.option(__t.i32()),
  spentThisMonth: __t.i32(),
  approvalAbove: __t.option(__t.i32()),
  online: __t.bool(),
  contactless: __t.bool(),
  atm: __t.bool(),
  international: __t.bool(),
  maxAuthorization: __t.option(__t.i32()),
  expiryNote: __t.option(__t.string()),
  provider: __t.string(),
  providerCardId: __t.option(__t.string()),
});
export type Cards = __Infer<typeof Cards>;

export const Deposits = __t.object("Deposits", {
  id: __t.string(),
  txHash: __t.string(),
  opId: __t.string(),
  fromAddress: __t.string(),
  assetCode: __t.string(),
  amountUnits: __t.f64(),
  creditedInr: __t.i32(),
  memo: __t.option(__t.string()),
  userId: __t.option(__t.string()),
  status: __t.string(),
  at: __t.string(),
});
export type Deposits = __Infer<typeof Deposits>;

export const Household = __t.object("Household", {
  id: __t.string(),
  name: __t.string(),
  budgetCap: __t.i32(),
  budgetSpent: __t.i32(),
});
export type Household = __Infer<typeof Household>;

export const Idempotency = __t.object("Idempotency", {
  key: __t.string(),
  actionId: __t.string(),
  receiptJson: __t.string(),
  createdAt: __t.string(),
});
export type Idempotency = __Infer<typeof Idempotency>;

export const Invites = __t.object("Invites", {
  code: __t.string(),
  memberId: __t.string(),
  createdBy: __t.string(),
  status: __t.string(),
  createdAt: __t.string(),
  acceptedAt: __t.option(__t.string()),
});
export type Invites = __Infer<typeof Invites>;

export const MemberCategories = __t.object("MemberCategories", {
  id: __t.string(),
  memberId: __t.string(),
  key: __t.string(),
  label: __t.string(),
  cap: __t.i32(),
  spent: __t.i32(),
  enabled: __t.bool(),
});
export type MemberCategories = __Infer<typeof MemberCategories>;

export const Members = __t.object("Members", {
  id: __t.string(),
  name: __t.string(),
  role: __t.string(),
  relationship: __t.option(__t.string()),
  monthlyLimit: __t.option(__t.i32()),
  spentThisMonth: __t.i32(),
  tempAllowanceAmount: __t.option(__t.i32()),
  tempAllowanceExpiresAt: __t.option(__t.string()),
  status: __t.string(),
});
export type Members = __Infer<typeof Members>;

export const ModuleConfig = __t.object("ModuleConfig", {
  id: __t.u32(),
  owner: __t.identity(),
});
export type ModuleConfig = __Infer<typeof ModuleConfig>;

export const Pool = __t.object("Pool", {
  id: __t.string(),
  network: __t.string(),
  account: __t.string(),
  assetCode: __t.string(),
  assetIssuer: __t.option(__t.string()),
  cryptoReserveUnits: __t.f64(),
  fiatFloatInr: __t.i32(),
  rateInrPerUnit: __t.f64(),
  privyWalletId: __t.option(__t.string()),
});
export type Pool = __Infer<typeof Pool>;

export const PreparedActions = __t.object("PreparedActions", {
  id: __t.string(),
  kind: __t.string(),
  source: __t.string(),
  payloadJson: __t.string(),
  subject: __t.string(),
  factsJson: __t.string(),
  factsHash: __t.string(),
  cta: __t.string(),
  note: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.string(),
  expiresAt: __t.string(),
  executedAt: __t.option(__t.string()),
  receiptJson: __t.option(__t.string()),
});
export type PreparedActions = __Infer<typeof PreparedActions>;

export const ProviderPool = __t.object("ProviderPool", {
  id: __t.string(),
  provider: __t.string(),
  balanceUsd: __t.f64(),
  updatedAt: __t.string(),
});
export type ProviderPool = __Infer<typeof ProviderPool>;

export const SyncState = __t.object("SyncState", {
  k: __t.string(),
  v: __t.string(),
});
export type SyncState = __Infer<typeof SyncState>;

export const Transactions = __t.object("Transactions", {
  id: __t.string(),
  merchant: __t.string(),
  memberId: __t.string(),
  cardId: __t.string(),
  amount: __t.i32(),
  direction: __t.string(),
  category: __t.string(),
  status: __t.string(),
  declineReason: __t.option(__t.string()),
  approvedBy: __t.option(__t.string()),
  at: __t.string(),
});
export type Transactions = __Infer<typeof Transactions>;

export const UserWallets = __t.object("UserWallets", {
  id: __t.string(),
  userId: __t.string(),
  address: __t.string(),
  chainType: __t.string(),
  source: __t.string(),
  linkedAt: __t.string(),
});
export type UserWallets = __Infer<typeof UserWallets>;

export const Users = __t.object("Users", {
  id: __t.string(),
  name: __t.string(),
  role: __t.string(),
  memberId: __t.string(),
  depositMemo: __t.string(),
  privyDid: __t.option(__t.string()),
  kycStatus: __t.string(),
  isAdmin: __t.bool(),
});
export type Users = __Infer<typeof Users>;

export const Withdrawals = __t.object("Withdrawals", {
  id: __t.string(),
  userId: __t.string(),
  toAddress: __t.string(),
  amountInr: __t.i32(),
  amountUnits: __t.f64(),
  status: __t.string(),
  at: __t.string(),
  txHash: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type Withdrawals = __Infer<typeof Withdrawals>;

