// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  role: __t.string(),
  memberId: __t.string().name("member_id"),
  depositMemo: __t.string().name("deposit_memo"),
  privyDid: __t.option(__t.string()).name("privy_did"),
  kycStatus: __t.string().name("kyc_status"),
  isAdmin: __t.bool().name("is_admin"),
});
