// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  toAddress: __t.string().name("to_address"),
  amountInr: __t.i32().name("amount_inr"),
  amountUnits: __t.f64().name("amount_units"),
  status: __t.string(),
  at: __t.string(),
  txHash: __t.option(__t.string()).name("tx_hash"),
  error: __t.option(__t.string()),
});
