// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptInviteReducer from "../accept_invite_reducer.js";
import AdminApproveOrderReducer from "../admin_approve_order_reducer.js";
import AdminRejectOrderReducer from "../admin_reject_order_reducer.js";
import AdminReviewKycReducer from "../admin_review_kyc_reducer.js";
import AdminSetProviderPoolReducer from "../admin_set_provider_pool_reducer.js";
import AppendAuditReducer from "../append_audit_reducer.js";
import ApplyFreezeReducer from "../apply_freeze_reducer.js";
import ApproveOnceReducer from "../approve_once_reducer.js";
import BindPrivyDidReducer from "../bind_privy_did_reducer.js";
import BootstrapPoolWalletReducer from "../bootstrap_pool_wallet_reducer.js";
import CancelActionReducer from "../cancel_action_reducer.js";
import CreateCardOrderReducer from "../create_card_order_reducer.js";
import DeclineApprovalReducer from "../decline_approval_reducer.js";
import DevLinkCardProviderReducer from "../dev_link_card_provider_reducer.js";
import DevResetReducer from "../dev_reset_reducer.js";
import ExecuteActionReducer from "../execute_action_reducer.js";
import ExpireActionReducer from "../expire_action_reducer.js";
import ExpireApprovalReducer from "../expire_approval_reducer.js";
import LinkWalletReducer from "../link_wallet_reducer.js";
import PrepareActionRowReducer from "../prepare_action_row_reducer.js";
import RecordDepositReducer from "../record_deposit_reducer.js";
import RecordOrderPaymentReducer from "../record_order_payment_reducer.js";
import SetCategoryReducer from "../set_category_reducer.js";
import SetChannelReducer from "../set_channel_reducer.js";
import SetSyncCursorReducer from "../set_sync_cursor_reducer.js";
import SubmitKycReducer from "../submit_kyc_reducer.js";
import WithdrawalMarkFailedReducer from "../withdrawal_mark_failed_reducer.js";
import WithdrawalMarkSentReducer from "../withdrawal_mark_sent_reducer.js";

export type AcceptInviteParams = __Infer<typeof AcceptInviteReducer>;
export type AdminApproveOrderParams = __Infer<typeof AdminApproveOrderReducer>;
export type AdminRejectOrderParams = __Infer<typeof AdminRejectOrderReducer>;
export type AdminReviewKycParams = __Infer<typeof AdminReviewKycReducer>;
export type AdminSetProviderPoolParams = __Infer<typeof AdminSetProviderPoolReducer>;
export type AppendAuditParams = __Infer<typeof AppendAuditReducer>;
export type ApplyFreezeParams = __Infer<typeof ApplyFreezeReducer>;
export type ApproveOnceParams = __Infer<typeof ApproveOnceReducer>;
export type BindPrivyDidParams = __Infer<typeof BindPrivyDidReducer>;
export type BootstrapPoolWalletParams = __Infer<typeof BootstrapPoolWalletReducer>;
export type CancelActionParams = __Infer<typeof CancelActionReducer>;
export type CreateCardOrderParams = __Infer<typeof CreateCardOrderReducer>;
export type DeclineApprovalParams = __Infer<typeof DeclineApprovalReducer>;
export type DevLinkCardProviderParams = __Infer<typeof DevLinkCardProviderReducer>;
export type DevResetParams = __Infer<typeof DevResetReducer>;
export type ExecuteActionParams = __Infer<typeof ExecuteActionReducer>;
export type ExpireActionParams = __Infer<typeof ExpireActionReducer>;
export type ExpireApprovalParams = __Infer<typeof ExpireApprovalReducer>;
export type LinkWalletParams = __Infer<typeof LinkWalletReducer>;
export type PrepareActionRowParams = __Infer<typeof PrepareActionRowReducer>;
export type RecordDepositParams = __Infer<typeof RecordDepositReducer>;
export type RecordOrderPaymentParams = __Infer<typeof RecordOrderPaymentReducer>;
export type SetCategoryParams = __Infer<typeof SetCategoryReducer>;
export type SetChannelParams = __Infer<typeof SetChannelReducer>;
export type SetSyncCursorParams = __Infer<typeof SetSyncCursorReducer>;
export type SubmitKycParams = __Infer<typeof SubmitKycReducer>;
export type WithdrawalMarkFailedParams = __Infer<typeof WithdrawalMarkFailedReducer>;
export type WithdrawalMarkSentParams = __Infer<typeof WithdrawalMarkSentReducer>;

